### ISSUE TITLE
createPixelBuffer -- RGB or BGR?

### ISSUE THREAD

**Issue by achigeor** [hollance/CoreMLHelpers#1]
In the function `createPixelBuffer` of `CVPixelBuffer+Helpers`, the description says the following:

> Creates a RGB pixel buffer of the specified width and height.

but in the function there is the following:
`  let status = CVPixelBufferCreate(nil, width, height,
                                   kCVPixelFormatType_32BGRA, nil,
                                   &pixelBuffer)`

Shouldn't that be `kCVPixelFormatType_32RGBA` or am I missing something?

**Comment by hollance** [comment]
I don't believe it matters how the colors are actually arranged in the pixel buffer. (That said, I should actually try this out to see whether it makes a difference or not to Core ML.)

**Comment by hollance** [comment]
I just checked it to make sure and indeed it does not matter. As long as the pixel format type is one of ARGB, ABGR, RGBA, or BGRA, Core ML will properly convert it to whatever format the model expects.

**Comment by achigeor** [comment]
Yes indeed it does not matter! Thanks a lot!

**Comment by spike322** [comment]
I need an rub Pixel Buffer, is it possible?
