### ISSUE TITLE
double 3x300x300 to Color 300x300

### ISSUE THREAD

**Issue by periscopiojoe** [hollance/CoreMLHelpers#13]
Hello @hollance , great job.
I have one question
¿how can I convert my input data before trainning from "double 3x300x300" to "Color 300x300"?
thanks

**Comment by periscopiojoe** [comment]
I have found a similiar issue from you [https://stackoverflow.com/questions/44529869/converting-uiimage-to-mlmultiarray-for-keras-model/44538525#44538525](url)
On the other hand, my output is now  "Multiarray (double 4x1917x1)" because input data is in a wrong type, and yours is "Multiarray (double),so do I need to convert the output data or will it be solved just fixing the input data ?

**Comment by periscopiojoe** [comment]
I have already tried input conversion but output still is wrong :(

**Comment by hollance** [comment]
This happens because Core ML does not understand that it has to interpret your input as an image. You need to tell coremltools that your input should be treated as an image.

**Comment by periscopiojoe** [comment]
Thanks,
And how can I do this? while conversion from TF to Core Ml? could you show me a sample, please?
Thanks

**Comment by periscopiojoe** [comment]
Is it the same that you explained here? [https://stackoverflow.com/questions/48773397/keras-image-classifier-for-coreml-image-input-asks-multiarray-instead-of-image](url)

**Comment by hollance** [comment]
I haven't used the TF converter, so no idea how to do it there.

**Comment by periscopiojoe** [comment]
I mean CoreML tools from keras-python, sorry

**Comment by periscopiojoe** [comment]
I read this from you "When converting your model to Core ML you also need to add input_names='camera frame' when you call coremltools.converters.keras.convert(), in addition to image_input_names='camera frame'. Otherwise coremltools won't see this input and doesn't know you want to treat it as an image."

> 

>

**Comment by hollance** [comment]
Yes that is correct.

**Comment by r4ghu** [comment]
@periscopiojoe If you are still facing this issue, the tf-coreml converter has `image_input_name` variable to be set for telling the converter that input is an image. For more infor, check this example notebook: https://github.com/tf-coreml/tf-coreml/blob/master/examples/style_transfer_example.ipynb
