### ISSUE TITLE
How are images being resized (what interpolation methods)?

### ISSUE THREAD

**Issue by bigmit2011** [hollance/CoreMLHelpers#14]
I'm going through your README and you show different options of resizing:

One use Vision (which does the resizing)

Or use:
  if let pixelBuffer = image.pixelBuffer(width: 224, height: 224)

I'm wondering how are these images being downsized. What interpolation methods are used when downsizing.  I realized playing with Coreml in Python that 
different interpolation methods affect the accuracy of the model. 

Thank you so much for this repository.

**Comment by hollance** [comment]
It uses one of the vImageScale methods to do the resizing. I'm not 100% sure but I think that is bilinear.
