### ISSUE TITLE
Nonsensical conversion error?

### ISSUE THREAD

**Issue by jbmaxwell** [hollance/CoreMLHelpers#17]
This popped up today: `Cannot convert value of type 'MultiArray<Double>' to specified type 'MultiArray<Double>'`
Unfathomably bizarre. I keep looking at it, expecting to see a difference between those two, but it never changes! Ha! Any thoughts?

**Comment by jbmaxwell** [comment]
I figured out what was up, though I can't say I understand why. I had a copy of the CoreMLHelpers in the framework I'm developing, but also had one in a utility app I'm building that uses the framework (dumb design, I know, and easily remedied). Getting rid of the one from the app, and calling the same function on the framework work removes the error. 

Strange though, since they are the same objects... It seems to me that must be a Swift bug, no?

**Comment by hollance** [comment]
Sometimes the Swift compiler gets confused but the error messages are not very helpful. That sounds like what happened here... ;-)
