### ISSUE TITLE
Not exactly an issue, but curious about concatenating MultiArrays?

### ISSUE THREAD

**Issue by jbmaxwell** [hollance/CoreMLHelpers#18]
I've noticed that trying to use a structure like `[MultiArray<Double>]` can be pretty dangerous, leading to EXC_BAD_ACCESS crashes. So, instead of doing this (which isn't ideal anyway), I'd like to concatenate MultiArrays into a larger _n_+1 dimensional MultiArray. That is, given a series of 4 x [3, 64, 64] MultiArrays, I'd like to create a [4, 3, 64, 64] array, but I'm not sure how to do this.

Currently, one of my [3, 64, 64] MultiArrays is created from an MLMultiArray (prediction) using `multiArray = MultiArray<Double>(mlMultiArray).reshaped([3, 64, 64])`, and 4 of these (predictions) are added to a `[MultiArray<Double>]` (but as I said, this seems pretty fragile—and as I recall, has been fragile for me in the past). I tried using something like `concatenatedMultiArray[n] = multiArray`, where _n_ is an index from 0 to 3, and `concatenatedMultiArray` is [4, 3, 64, 64], but clearly I'm not able to index MultiArray this way. Any tips?

**Comment by hollance** [comment]
Can you add a Concat layer to the model? If not, it’s a matter of allocating a large enough memory buffer and copying things by hand. The MultiArray class is really an experimental thing, I wouldn’t use it for serious work.

**Comment by jbmaxwell** [comment]
Yikes! Is it relatively recently that you've started referring to MultiArray as "experimental"? I've been using it for a while without issue (as long as I avoid [MultiArray] structures—really not sure why that causes problems(??)), so I suppose I'm not too concerned, but it is integrated in my code fairly deeply now. Would you recommend that I remove/replace it?

As far as the concat goes, I could look into the possibility of a concat in my model. For now I've done it by hand, and it seems fine.

**Comment by hollance** [comment]
Using MultiArray is mostly fine, but there is a known issue with creating a MultiArray derived from another one. In that case it gives the wrong answers. There is a failing test case in the repo in case you're wondering exactly what I'm talking about.

**Comment by jbmaxwell** [comment]
Ah, okay. Great. Yes, as long as I avoid that I haven't had any trouble. They're handy and helpful (as "helpers", I guess they should be!)

**Comment by jbmaxwell** [comment]
Quick question: Is there a simple way to get a 3D slice from a 4D MultiArray? I have a MultiArray [4, 3, 64, 64]—i.e., just 4 x [3, 64, 64] images concatenated together—and I want to get the nth [3, 64, 64] sub matrix out.

**Comment by hollance** [comment]
Grab the pointer to the start of the MLMultiArray and increment it by `n*3*64*64` and then copy the next 3*64*64 elements. It’s just a memcpy, basically. 

If you want to use MultiArray (without the ML) then you shouldn’t use the pointer but use a for loop and the subscript (because otherwise any reshaping or transposing is ignored). So now you need to loop through the array to copy out the items, which is slower than a single memcpy.

**Comment by jbmaxwell** [comment]
Thanks, I did wind up iterating over the multiArray.array, but I'll check out the memcpy version.
