### ISSUE TITLE
CVPixelBufferRef exc_bad_access

### ISSUE THREAD

**Issue by yao2030** [hollance/CoreMLHelpers#19]
Hello, as we know, coreml can output a color image (CVPixelbufferRef),but when the coreml model is used in Objective-C project, it always crashed on the output pixelbufferref, saying "exc_bad_access". When used in Swift project, it works well. 
I setup a project at [Repo](https://github.com/yao2030/CoreMLTest), could you help me find out how to fix this problem, as I have to use Objective-C due to some reason.

**Comment by hollance** [comment]
What is the error message you're getting and at what line in the code does it crash?

**Comment by yao2030** [comment]
It crashes on the line: 
`    CIImage *ciimage = [[CIImage alloc] initWithCVPixelBuffer:output.outputImage];
`
and the error message is: EXC_BAD_ACCESS

**Comment by hollance** [comment]
What is the value of `error` at this point? What is the value of `output`? And what is the value of `output.outputImage`?

**Comment by yao2030** [comment]
error is nil, output is an instance of StarryNightOutput, value of output.outputImage is exc_bad_access so it should mean value of output.outputImage is already released ?

**Comment by hollance** [comment]
The good news: Your model looks correct, it works fine from Python. The bad news: Core ML in Objective-C seems to return a CVPixelBuffer object that is invalid (size 0). Have you tried running it from Swift, to see if that works?

**Comment by yao2030** [comment]
It works well in swift

**Comment by hollance** [comment]
In that case I suggest filing a bug report with Apple. As a workaround you can use Swift, or perhaps use the MLModel API directly (not the generated class), or make the model output an MLMultiArray instead of a pixel buffer and convert this to an image yourself.
