### ISSUE TITLE
How to encrypt coreml models

### ISSUE THREAD

**Issue by yao2030** [hollance/CoreMLHelpers#21]
Sorry this question is not related to your CoremlHelpers repo. I have a question as to how to encrypt 
coreml models inside ios app, as it's really easy to pick up mlmodelc files from the ipa file, so others can use the valuable model which can harm the business.
Thanks.

**Comment by hollance** [comment]
My book has a chapter discussing this issue (but no code sample as encryption is tricky). https://leanpub.com/coreml-survival-guide/
