### ISSUE TITLE
Converting multiarray to grayscale image

### ISSUE THREAD

**Issue by mevinDhun** [hollance/CoreMLHelpers#22]
I have a coreml model which returns a multi array containing grayscale data.
![screenshot 2019-03-02 at 15 21 28](https://user-images.githubusercontent.com/17478561/53681175-f1f16680-3cfe-11e9-9698-26e97df1ffaf.png)

I printed the coreml output and it is  in this format:
```swift
(Double 1 x 1 x 1 x 240 x 320 array)
```
I tried the following codes to convert it to an image but always end up with a black/white output
```swift
output.reshaped(to: [1, 240, 320]).image()
output.reshaped(to: [1, 240, 320]).image(min: 0, max: 255, channel: 0, axes: (0,1,2))
output.image(min: 0, max: 255, axes: (0, 1, 2))
```
This one crashes with index out of range at ```let width = self.shape[widthAxis].intValue```
```swift
output.reshaped(to: [240, 320]).image()
```
Can anyone tell me how to fix this?

**Comment by hollance** [comment]
You can change the output type of the Core ML model so that it automatically gives you the image in a CVPixelBuffer object instead of an MLMultiArray. More about this in my book: https://leanpub.com/coreml-survival-guide

**Comment by mevinDhun** [comment]
Thanks for the fast reply! I had used the python script from this link to convert the output to pixelBuffer:
[https://forums.developer.apple.com/thread/81571#241998](https://forums.developer.apple.com/thread/81571#241998)
But when i tried converting it to a uiimage/cgimage, it was always null. That's why i reverted back to using MLMultiArray

**Comment by mevinDhun** [comment]
I fixed it by using 
```
output.reshaped(to: [1, 240, 320]).image(min:-1, max: 1)
```
