### ISSUE TITLE
Crash but not sure is issue

### ISSUE THREAD

**Issue by healmax** [hollance/CoreMLHelpers#24]
when i receive the camera call back "func captureOutput(_ output: AVCaptureOutput, didOutput sampleBuffer: CMSampleBuffer, from connection: AVCaptureConnection)" from AVCaptureVideoDataOutputSampleBufferDelegate, and i get the piexelBuffer from CMSampleBuffer, and rotate  piexelBuffer use "rotate90PixelBuffer", and use this piexelBuffer change to MTLTexture then crash

**Comment by hollance** [comment]
What is the error message?

It’s possible you need to copy the rotated pixel buffer into an IOSurface-backed buffer first. 

There is an open pull request that shows how to do this. I just haven’t integrated that code into the repo yet.
