### ISSUE TITLE
Create 'createCGImage' from Double

### ISSUE THREAD

**Issue by not-Ian** [hollance/CoreMLHelpers#26]
I have a CoreML model I've created which does image segmentation of a single class. It outputs a 2-channel image of size 1024x1024. The first channel is the foreground, the second is background, all of type *Double*.

I've been trying to use the [`createCGImage(fromFloatArray: ...)` function](https://github.com/hollance/CoreMLHelpers/blob/master/CoreMLHelpers/MLMultiArray%2BImage.swift#L237) to convert the model's output to a UIImage since it's so much faster than the previous way I've been trying, but I haven't been able to find a way for it to properly handle the Double data I'm giving it. 

If I change the max value to anything less than 255 it just makes a quilt/checkerboard black/white image that doesn't react to any camera input. When the max is 255 it outputs all black.

Any ideas?

**Comment by not-Ian** [comment]
I should note: I only need to view 1 channel of my network's output. I tried removing the 'redBuffer=...' and 'greenBuffer=...' code and replacing them with 'blueBuffer=...' in the 'vImageConvert_PlanarFToBGRX8888' init. I assume this will still be needed for my use case.

**Comment by hollance** [comment]
I would change the output type of the neural network from doubles to floats. You can do this in the mlmodel itself using coremltools. All you have to do is change the data type of the output from DOUBLE to FLOAT.

**Comment by not-Ian** [comment]
Awesome - I thought that might have been a possible solution but must not have looked hard enough. I'll look at coremltools documentation to see where one can do this.
