### ISSUE TITLE
use with macOS/NSImage

### ISSUE THREAD

**Issue by bkonk** [hollance/CoreMLHelpers#28]
Could you provide a version or suggest edits for use with macOS/NSImage? Would this be a huge project or could this be done by slight modifications?

**Comment by hollance** [comment]
You should already be able to use it with CGImage on the Mac.

**Comment by bkonk** [comment]
This would be using functions from UIImage+CVPixelBuffer and substituting CGImage alternatives for UIImage commands?

**Comment by hollance** [comment]
You'd use the functions from CGImage+CVPixelBuffer. :-)

**Comment by bkonk** [comment]
That makes sense... for some reason none of the CGImage+ files were showing up before but I recloned and see them now. Thanks!
