### ISSUE TITLE
Is there any way to make the returned CVPixelbuffer backed by an IOSurface ?

### ISSUE THREAD

**Issue by yao2030** [hollance/CoreMLHelpers#29]
https://github.com/hollance/CoreMLHelpers/blob/f99c04de1693f9be381c46f8d1c9eefa4859694a/CoreMLHelpers/CVPixelBuffer%2BHelpers.swift#L143

Is there any way to make the returned CVPixelbuffer backed by an IOSurface ?

**Comment by hollance** [comment]
You can use the `copyToMetalCompatible()` function on the pixel buffer to do this.

Another way would be to change the rotation code to not use `CVPixelBufferCreateWithBytes()` to allocate the pixel buffer, but first create the pixel buffer with the desired attributes, then write directly into its memory.

**Comment by yao2030** [comment]
Thanks a lot
