### ISSUE TITLE
Carthage - no shared framework schemes

### ISSUE THREAD

**Issue by rusito-23** [hollance/CoreMLHelpers#33]
Chartage update fails with message:

```
*** Skipped building CoreMLHelpers due to the error:
Dependency "CoreMLHelpers" has no shared framework schemes
```

My Cartfile:

```
github "hollance/CoreMLHelpers"
```

I could not find any .xcworkspace file in the repo, maybe that's the problem, anyway I will try copying the files directly into my project!

**Comment by AlanMoMo** [comment]
same problem

**Comment by sharmin03** [comment]
Same problem :/
