### ISSUE TITLE
Swift Package Manager Support?

### ISSUE THREAD

**Issue by gsabran** [hollance/CoreMLHelpers#36]
Would it be possible to add support for SPM?

**Comment by hollance** [comment]
Probably, but I'm not a fan of package managers and so I personally don't use them. Just copy the files you need into your projects (it's probably only one or two files).

**Comment by raphimulator** [comment]
bump.
@shu223 has already done this [in his fork](https://github.com/shu223/CoreMLHelpers.git) and has even filed a [pull request](https://github.com/hollance/CoreMLHelpers/pull/32).
