### ISSUE TITLE
[Feature] MLMultiArray -> UIImage without premultiplied alpha

### ISSUE THREAD

**Issue by jiangwei221** [hollance/CoreMLHelpers#37]
Hi Matthijs:
Thanks for the great tool, it's really helpful!
I'm working on an image to image model, and alpha channel is part of the output. 
The model outputs a [4, height, width] MLMultiArray, 4 channels are RGBA. And the value for the RGBA are not premultiplied. 
I used to tool to convert the output to UIImage, it works, but because the `fromByteArrayRGBA` function uses `premultipliedLast`, so the RGB values in the UIImage are already multipied with Alpha channel.
I tried to add:
```
@nonobjc public class func fromByteArrayRGBA2(_ bytes: [UInt8],
                                                 width: Int,
                                                 height: Int) -> CGImage? {
      return fromByteArray(bytes, width: width, height: height,
                           bytesPerRow: width * 4,
                           colorSpace: CGColorSpaceCreateDeviceRGB(),
                           alphaInfo: .last)
    }
```
But it would return a nil when I can .image method.
Can you help me on this question?

**Comment by hollance** [comment]
I suppose you could multiply the RGB values with A for every pixel before calling `fromByteArrayRGBA`.

**Comment by jiangwei221** [comment]
I think I need to divide RGB by A before calling `fromByteArrayRGBA`? Because RGB value will be multiplied with A inside the function. 
My current workaround is let the output be 2 MLMultArray: one [3, height, width] and [1, height, width], then I convert them to 2 UIImage, one RGB and one grayscale. Then I concat the two images using OpenCV.
