### ISSUE TITLE
Need help to adjust bbox for cropped images

### ISSUE THREAD

**Issue by iosfitness** [hollance/CoreMLHelpers#40]
Hello,

I have a feature wherein I allow the users to crop the presets (top, bottom, left, and right). This works fine to get the desired detections. The only issue I encounter is adjusting the bbox coordinates returned by vision. 

I am not able to able to figure out the right approach to achieve that. It is more inaccurate when any of the combinations (top+bottom) or (left+right) is applied

Below is the code snippet I am currently using

```
//imageAreaRect : Rendering frame on device
//topCropRatio : range from 0.0 to 0.30
//bottomCropRatio : range from 0.0 to 0.30
	let width = imageAreaRect.width   
	let height = imageAreaRect.height - ((imageAreaRect.height * CGFloat(topCropRatio)) + (imageAreaRect.height * CGFloat(bottomCropRatio)))
			
let objectBounds = VNImageRectForNormalizedRect(objectBoundingBox.boundingBox, Int(width), Int(height))

//BBOX Adjustment
				if(topCropRatio > 0.0 &&  bottomCropRatio > 0.0){
					adjustY =  -(height+offsetY) - (height * CGFloat( topCropRatio))
					adjustY +=  (height * CGFloat( bottomCropRatio))
					adjustY = adjustY - (objectBounds.size.height*4)
				}
				else
				{
					if( topCropRatio > 0.0){
						adjustY =  -(height+offsetY) - (height * CGFloat( topCropRatio))
						adjustY = adjustY + objectBounds.size.height + 10 //Extra padding
					}
					
					if(info!.pixelBufferConfig.bottomCropRatio > 0.0){
						adjustY =  -(height+offsetY) + (height * CGFloat bottomCropRatio))
						adjustY =  adjustY - objectBounds.size.height
						if(UIDevice.current.orientation.isPortrait){
							adjustY =  adjustY - objectBounds.size.height
						}
						else{
							adjustY =  adjustY + objectBounds.size.height
						}
					}
				}
```

I had a look at this thread as well https://github.com/apple/turicreate/issues/1016

I am currently using the below technique :

```
if orientation == .left || orientation == .right || orientation == .rightMirrored || orientation == .leftMirrored {
												req.imageCropAndScaleOption = .scaleFit
											} else {
												req.imageCropAndScaleOption = .scaleFill
											}
```

Any input will be appreciated. Thanks in advance

**Comment by hollance** [comment]
The bbox coordinates are returned as normalized numbers (between 0 and 1), with (0, 0) in the lower-left corner of the image. But the image here is the image that Vision passed to Core ML. 

If you used crop & scaling options, or set a crop rect, then you have to translate these [0, 1] coordinates back to the uncropped image coordinates. How exactly you need to do that depends on how you cropped the image.

Also note that a UIImageView (or a AVCaptureVideoPreviewLayer) can do its own cropping, depending on how you set that up, so there may be multiple coordinate system transforms you need to do.

**Comment by iosfitness** [comment]
@hollance Thanks for the response

I tried the below but still, it seems to have not had accurate issues

```
let transform = CGAffineTransform(scaleX:1, y: -1).translatedBy(x:0, y: -inputSize.height)
let translate = CGAffineTransform.identity.scaledBy(x: width, y:height)

let detectionBBox = objectBoundingBox.boundingBox.applying(translate).applying(transform)
```

Should I be using ```VNNormalizedRectForImageRect``` and then perform some translation?

Any reference link you could share which has some similar implementation

**Comment by hollance** [comment]
I would suggest approaching this in steps: first use an image without cropping. Can you get the bboxes to show up in the correct place now?

**Comment by iosfitness** [comment]
Yes, I am able to see the boxes in the right place without applying any crop logic. The issue only occurs when I plot on a cropped image

**Comment by hollance** [comment]
The next step is to make a UIImageView that has exactly the same dimensions as your image (before cropping) and that has a content mode of Top Left. Then draw the original image in there. Also draw a bounding box of (0, 0) - (1, 1) in there to see if that surrounds the cropping area. If not, your bounding boxes may actually be correct but they're not being drawn correctly.

**Comment by iosfitness** [comment]
Thanks. I will follow the the instructions and share the results.

**Comment by hollance** [comment]
All I have is this: https://github.com/hollance/coreml-survival-guide/tree/master/MobileNetV2%2BSSDLite

But that doesn't use cropping, I think.
