### ISSUE TITLE
pixelBuffer not public

### ISSUE THREAD

**Issue by raphimulator** [hollance/CoreMLHelpers#41]
When CoreMLHelpers is used as a Swift Package, some functions cannot be called unless they are `public`. [`CGImage+CVPixelBuffer::pixelBuffer`](https://github.com/hollance/CoreMLHelpers/blob/f60d1b24cb8cae6e22b6a974e3df855ebba6af58/CoreMLHelpers/CGImage%2BCVPixelBuffer.swift#L52) is one of those.

**Comment by hollance** [comment]
Thanks, fixing this.
