### ISSUE TITLE
UI Image to kCVPixelFormatType_422YpCbCr8FullRange pixel format not working

### ISSUE THREAD

**Issue by harshitshah4** [hollance/CoreMLHelpers#50]
How to convert UI Image to kCVPixelFormatType_422YpCbCr8FullRange ?

pixelBuffer  expects width, height, pixelFormatType, colorSpace and  alphaInfo, what should be the appropriate values for these paramaters, especially for colorSpace

**Comment by hollance** [comment]
YpCbCr formats are a bit different than the RGB formats in that they contain two separate "bit planes" that need to be combined to make the final color. vImage has functions for this.

**Comment by harshitshah4** [comment]
Can you please point to the resource for the same ?

Basically my code download image from url, needs to convert it to required pixel format, and then finally output CMSampleBuffer.

**Comment by hollance** [comment]
Probably something like `vImageConvert_ARGB8888To444AYpCbCr8`

**Comment by harshitshah4** [comment]
Thanks for the reply, closing this issue.
