### ISSUE TITLE
resizePixelBuffer does not keep aspect ratio

### ISSUE THREAD

**Issue by cagkanciloglu** [hollance/CoreMLHelpers#8]
Hi,
I'm trying to resize a 1280x720 image's pixel buffer to 300x300. But the resulted pixel buffer is like squashed.
What I want is to get an image which has 300 height, its appropriate width and black borders on sides.
Basically it should produce images like this:
![img_0590](https://user-images.githubusercontent.com/1947752/38470837-52a6de28-3b71-11e8-8bc1-044251e54a42.jpg)

How can i archive this?
Thanks

**Comment by hollance** [comment]
This is correct, the current resizing code does not preserve the aspect ratio. This requires changes in the resizePixelBuffer function.

**Comment by cagkanciloglu** [comment]
Thanks for the response @hollance 
What would the changes be? In OpenCV i do this resize procedure like this:
`   aspect_ratio = float(desired_size)/max(old_size)
     new_size = tuple([int(x* aspect_ratio) for x in old_size])
     im = cv2.resize(im, (new_size[1], new_size[0]))
     
     // for the border
     delta_w = desired_size - new_size[1]
     delta_h =  desired_size - new_size[0]
     top, bottom = delta_h//2, delta_h-(delta_h//2)
     left, right = delta_w//2, delta_w-(delta_w//2)
    color = [0, 0, 0]
    new_im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT,
        value=color) `

How could we port this to pixel buffer?
