### ISSUE TITLE
slicing MultiArray and apply sigmoid OR softmax ?

### ISSUE THREAD

**Issue by amanmeetgarg** [hollance/CoreMLHelpers#9]
I have a large MLMultiArray as an output of the coreml model of dimension (1,40,30,90). I convert it to a MultiArray and want to proceed further.

I want to slice it into three subarrays of dimensions (1,40,30,45), (1,40,30,9), (1,40,30,36) .. 

Then I would need to apply softmax / sigmoid function to the values in these three arrays .. 

Is there a direct way ( e.g. MultiArray. reshape ) for the slicing and then to apply the nonlinearities ?

Your help is much appreciated.

Thanks @hollance .

**Comment by hollance** [comment]
There is not currently. However, depending exactly on how you want to apply the softmax / sigmoid you may want to use Accelerate functions directly on the array data. So instead of slicing you would do some pointer magic.
